inputs:
  stable_branch:
    description: 'Name of the stable branch'
    required: false
    default: 'master'
  development_branch:
    description: 'Name of the development branch'
    required: false
    default: 'devel'
  allow_ff:
    description: 'Allow fast forward merge'
    required: false
    default: false
