name: CI

on:
  schedule:
    - cron:  '*/2 * * * *'

jobs:
  automerge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Automatic Merge
      uses: lots0logs/gh-action-auto-merge@1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
