name: 'Nightly Merge'

on:
  push:
    branches:
      - master

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Nightly Merge
      uses: ./.github/actions/nightly-merge
      with:
        stable_branch: 'master'
        development_branch: 'devel'
        allow_ff: false
        user_name: 'The user name'
        user_email: 'email@example.com'
        push_token: 'FOO_TOKEN'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOO_TOKEN: ${{ secrets.FOO_TOKEN }}
