name: 'Nightly Merge'

on:
  schedule:
    - cron:  '*/0 0 * * *'

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@master
      with:
        stable_branch: 'master'
        development_branch: 'devel'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
