name: 'Nightly Merge'

on:
  schedule:
    - cron:  '*/1 * * * *'

jobs:
  automerge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Nightly Merge
      uses: robotology/gh-action-nightly-merge@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
